In [1]:
import math
import numpy as np
import random
#from numpy import nan

# 1

In [2]:
def import_data(filename):
    with open(filename,'r') as f:
        
        X = []
        y = []
        
        for line in f:
            line = line.replace("?","nan").strip().split(',')
            
            floatList = [float(i) for i in line]

            tail = floatList.pop(-1)
            head = floatList           

            X.append(head)
            
            y.append(tail)          
            y = [int(i) for i in y]

    return X, y

print(import_data('arrhythmia.data')[0])
print('\n')
print(import_data('arrhythmia.data')[1])


[[75.0, 0.0, 190.0, 80.0, 91.0, 193.0, 371.0, 174.0, 121.0, -16.0, 13.0, 64.0, -2.0, nan, 63.0, 0.0, 52.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 44.0, 20.0, 36.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 40.0, 0.0, 0.0, 0.0, 60.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 36.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 32.0, 0.0, 0.0, 0.0, 56.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 80.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, 52.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 52.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.2, 0.0, 6.1, -1.0, 0.0, 0.0, 0.6, 2.1, 13.6, 30.8, 0.0, 0.0, 1.7, -1.0, 0.6, 0.0, 1.3, 1.5, 3.7, 14.5, 0.1, -5.2, 1.4, 0.0, 0.0, 0.0, 0.8, -0.6, -10

# 2

In [3]:
#2a

def median(lst):
    
    length = len(lst)
    sort = sorted(lst)
    
    return ((sort[(length // 2)] + sort[~length // 2]) / 2)

def addmedian(lst,median):
        
    emptyList = []
    for i in range(len(lst)):
        if (math.isnan(lst[i]) != True):
            emptyList.append(lst[i])
        else:
            emptyList.append(median)
    listWithMedian = emptyList
    
    return listWithMedian

def inmute_missing(X):
    
    transposed = list(map(list, zip(*X)))
    
    emptyList = [[]]*len(transposed)
    emptyList2 = [[]]*len(transposed)
    emptyList3 = [[]]*len(transposed)
    
    for i in range(len(transposed)):
        emptyList[i] = [j for j in transposed[i] if math.isnan(j) != True]
    noNanList = emptyList
    
    for i in range(len(transposed)):
        emptyList3[i] = [j for j in X[i] if math.isnan(j) != True]
    
    medianList = []
    
    for i in noNanList:
        medianList.append(median(i))
    
    
    for j in X:
        for i in range(len(medianList)):
            emptyList2[i] = addmedian(j, medianList[i])
        X = emptyList2
        
        
        return X
    
X1 = (import_data('arrhythmia.data')[0])
y1 = (import_data('arrhythmia.data')[1])

print(inmute_missing(X1))

X2 = (inmute_missing(X1))

[[75.0, 0.0, 190.0, 80.0, 91.0, 193.0, 371.0, 174.0, 121.0, -16.0, 13.0, 64.0, -2.0, 47.0, 63.0, 0.0, 52.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 44.0, 20.0, 36.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 40.0, 0.0, 0.0, 0.0, 60.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 36.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 32.0, 0.0, 0.0, 0.0, 56.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 80.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, 52.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 52.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.2, 0.0, 6.1, -1.0, 0.0, 0.0, 0.6, 2.1, 13.6, 30.8, 0.0, 0.0, 1.7, -1.0, 0.6, 0.0, 1.3, 1.5, 3.7, 14.5, 0.1, -5.2, 1.4, 0.0, 0.0, 0.0, 0.8, -0.6, -1

2b

Median is better because it avoids outliers that are small in numbers but are so radically different that they influence the mean. By taking median we avoid it and go straight to the middle, where numbers that are most often popping are located, making it much more accurate and almost improbable to be skewed by outliers

In [4]:
#2c

def discard_missing(X,y):
    
    emptyList = [[]]*len(X)
    for i in range(len(X)):
        emptyList[i] = [j for j in X[i] if math.isnan(j) != True]
    X = emptyList
    
    yList = [j for j in y if math.isnan(j) != True]
    y = yList
    
    return X, y

print(discard_missing(X1,y1)[0])
print('\n')
print(discard_missing(X1,y1)[1])

[[75.0, 0.0, 190.0, 80.0, 91.0, 193.0, 371.0, 174.0, 121.0, -16.0, 13.0, 64.0, -2.0, 63.0, 0.0, 52.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 44.0, 20.0, 36.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 40.0, 0.0, 0.0, 0.0, 60.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 36.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 32.0, 0.0, 0.0, 0.0, 56.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 80.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 40.0, 52.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 52.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 48.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 44.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.2, 0.0, 6.1, -1.0, 0.0, 0.0, 0.6, 2.1, 13.6, 30.8, 0.0, 0.0, 1.7, -1.0, 0.6, 0.0, 1.3, 1.5, 3.7, 14.5, 0.1, -5.2, 1.4, 0.0, 0.0, 0.0, 0.8, -0.6, -10.7, -

# 3

In [5]:
#3a

def shuffle_data(X, y):
    
    emptyList = []
    emptyList2 = []
    orderedList = []
    
    for i in range(len(X)):
        orderedList.append(i)

    shuffledList = np.array(orderedList)
    
    np.random.shuffle(shuffledList)

    for i in shuffledList:
        emptyList.append(X[i])
        emptyList2.append(y[i])
    X = emptyList
    y = emptyList2
    
    return X, y

X2, y2 = discard_missing(X1,y1)

print(shuffle_data(X2,y2)[0])
print('\n')
print(shuffle_data(X2,y2)[1])

[[20.0, 1.0, 157.0, 57.0, 81.0, 151.0, 363.0, 166.0, 80.0, 43.0, 42.0, 72.0, 42.0, 75.0, 0.0, 48.0, 0.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 24.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 36.0, 0.0, 0.0, 40.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 24.0, 0.0, 0.0, 0.0, 56.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0, 40.0, 0.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 56.0, 20.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0, 60.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 44.0, 48.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 72.0, 20.0, 0.0, 0.0, 56.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 36.0, 0.0, 0.0, 36.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 36.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52.0, 32.0, 0.0, 0.0, 28.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 6.1, 0.0, 0.0, 0.0, 0.4, 1.9, 14.6, 27.9, 0.1, 0.0, 7.6, -0.9, 0.0, 0.0, 1.4, 2.4, 20.2, 37.0, 0.0, 0.0, 1.4, -0.5, 0.0, 0.0, 1.0, 0.5, 3.0, 5.3, 

In [6]:
#3b

def compute_std(X):
    std = []
    transposed = list(map(list, zip(*X)))
    for i in transposed:
        mean = sum(i) / len(i)
        stdSingle = math.sqrt(sum((j-(sum(i) / len(i)))**2 for j in i) / (len(i)))
        std.append(stdSingle)
    return std

print (compute_std(X2))

[16.448405933617636, 0.49740398196847574, 37.129199666717625, 16.572439720263766, 15.347388347150025, 44.79265077831562, 33.34847024285476, 35.59363289630149, 25.79805813293285, 45.38114986013732, 57.4959720589143, 29.346675904427705, 40.946301140649936, 59.959044214556805, 29.183458753565326, 21.058575992610642, 26.7042872958858, 10.087886179390093, 6.793809401947557, 13.809382199417174, 14.317743632149325, 0.06637168141592904, 0.13969622906979556, 0.04698398358760035, 0.06637168141592886, 1.8922785074406774, 16.422577399349375, 23.095403912592946, 24.92055982165591, 13.426721206332255, 7.721942559922269, 14.8991077576583, 13.579271153457682, 0.1234782855077507, 0.0811980057677108, 0.04698398358760039, 0.10459244826170672, 5.0094138609233045, 22.517554672377873, 24.728602836824674, 24.738226960116513, 17.925392059203386, 9.905414532390939, 20.248251742932197, 13.23946525972178, 0.1540909747731494, 0.10459244826170638, 0.1234782855077507, 0.11444705448121731, 13.005213657205346, 26.121

In [7]:
#3c

def remove_outlier(X, y):
    
    std = []
    mean = []
    
    transposed = list(map(list, zip(*X)))
    for i in transposed:
        mean.append(sum(i) / len(i))
        stdSingle = math.sqrt(sum((j-(sum(i) / len(i)))**2 for j in i) / (len(i)))
        std.append(stdSingle)
        
    outlierFreeList = []
    
    j = 0
    for i in transposed:
        outliers = []
        lowCut = mean[j] - std[j]*2
        highCut = mean[j] + std[j]*2
        outliersGone = [x == 'nan' if (x < lowCut or x > highCut) else x for x in i]
        outlierFreeList.append(outliersGone)               
        j = j+1
    
    backTranspose = list(map(list, zip(*outlierFreeList)))
    
    X = []
    j = 0
    for i in backTranspose:
        part = [x for x in i if x != False]
        X.append(part)
        
    for i in range(len(y)):
        outliers = []
        lowCut = (sum(y) / len(y)) - (math.sqrt(sum((j-(sum(y) / len(y)))**2 for j in y) / (len(y))))*2
        highCut = (sum(y) / len(y)) + (math.sqrt(sum((j-(sum(y) / len(y)))**2 for j in y) / (len(y))))*2
        outliersGone2 = [x == 'nan' if (x < lowCut or x > highCut) else x for x in y]
    
    y = []
    for i in outliersGone2:
        y = [x for x in outliersGone2 if x != False]
    
    return X, y

print(remove_outlier(X2, y1))

X3 = remove_outlier(X2, y1)[0]
Y3 = remove_outlier(X2, y1)[1]


([[75.0, 190.0, 80.0, 91.0, 193.0, 371.0, 174.0, 121.0, -16.0, 13.0, 64.0, -2.0, 63.0, 52.0, 44.0, 32.0, 44.0, 20.0, 28.0, 52.0, 40.0, 60.0, 52.0, 56.0, 36.0, 32.0, 32.0, 40.0, 52.0, 28.0, 48.0, 48.0, 32.0, 52.0, 52.0, 36.0, 52.0, 48.0, 32.0, 56.0, 44.0, 32.0, -0.2, 6.1, -1.0, 0.6, 2.1, 13.6, 30.8, 1.7, -1.0, 0.6, 1.3, 1.5, 3.7, 14.5, 0.1, 1.4, 0.8, -0.6, -10.7, -15.6, 0.4, -3.9, -0.8, -1.7, -10.1, -22.0, 5.7, -1.0, -0.1, 1.2, 14.1, 22.5, -2.5, 0.8, 1.0, 0.4, -4.8, -2.7, 0.1, -6.0, -0.8, -0.6, -24.0, -29.7, 2.0, -6.4, 0.2, 2.9, -12.6, 15.2, -0.1, 8.4, -10.0, 0.6, 5.9, -3.9, 52.7, -0.3, 15.2, -8.4, 0.9, 5.1, 17.7, 70.7, -0.4, 13.5, -4.0, 0.9, 3.9, 25.5, 62.9, -0.3, 9.0, -0.9, 0.9, 2.9, 23.3], [56.0, 1.0, 165.0, 64.0, 81.0, 174.0, 401.0, 149.0, 39.0, 25.0, 37.0, 31.0, 53.0, 48.0, 24.0, 64.0, 24.0, 32.0, 24.0, 40.0, 48.0, 44.0, 20.0, 24.0, 60.0, 20.0, 24.0, 52.0, 16.0, 32.0, 52.0, 20.0, 44.0, 48.0, 32.0, 48.0, 44.0, 32.0, 48.0, 40.0, 28.0, 48.0, 28.0, -0.6, 7.2, 0.4, 1.5, 17.2, 26.5, 5.5,

In [8]:
#3d 

def standardize_data(X):
    
    std = []
    mean = []
    
    transposed = list(map(list, zip(*X)))
    for i in transposed:
        mean.append(sum(i) / len(i))
        stdSingle = math.sqrt(sum((j-(sum(i) / len(i)))**2 for j in i) / (len(i)))
        std.append(stdSingle)
        
    transposed2 = list(map(list, zip(*X)))
    
    for i in range(len(transposed2)):
        k = 0
        for j in transposed2[i]:
            if std[i] == 0:
                transposed2[i][k] = j
            else:
                transposed2[i][k] = ((j-mean[i])/std[i])
            k = k+1
    
    return transposed2

#time and space complexity here is O(m,n) since they (m and n) are the dimensions of the data set

print(standardize_data(X3))

[[1.2358971817655735, 0.33427596217648553, 0.23936846537763415, 0.28682221377705985, 1.2358971817655735, 5.696549531311589, -0.42498401221432547, 0.0020997233805057016, -0.23516901861662273, 0.04955347177993139, 0.6189984525730396, -0.18771527021719706, 0.23936846537763415, -0.8995214962085823, -0.23516901861662273, -0.09280777341834567, -0.09280777341834567, -0.14026152181777135, 1.1409896849667223, 0.3817297105759112, -0.9944289930074337, -0.18771527021719706, -0.6147990058120283, 0.3817297105759112, -0.42498401221432547, -0.23516901861662273, -0.7097065026108796, -0.8520677478091566, 0.33427596217648553, 0.09700722017935708, 0.19191471697820844, 0.4291834589753369, 0.04955347177993139, 0.14446096857878277, 0.9511746913690194, -0.23516901861662273, 0.04955347177993139, -0.6622527542114539, 0.6189984525730396, -0.18771527021719706, -0.28262276701604844, -0.42498401221432547, -0.8995214962085823, -0.7097065026108796, -0.42498401221432547, 1.2358971817655735, 0.9511746913690194, -0.8995

# 4

In [9]:
def import_data2(filename):
    with open(filename,'r') as f:
        headers = f.readline()
        
        X = [[] for i in range(8)]
        y = []
        
        # REFERENCE:
        #
        # x[0] - PassengerId
        # y - Survived
        # x[1] - Pclass
        # nan - Name
        # x[2] - Sex
        # x[3] - Age
        # x[4] - SibSp
        # x[5] - Parch
        # nan - Ticket
        # x[6] - Fare
        # nan - Cabin
        # x[7] - Embarked
        
        info = f.read().strip().split('\n')
        for line in info:
            line = line.strip().split(',')
            
            X[0].append(int(line[0]))
            y.append(int(line[1]))
                        
            X[1].append(int(line[2]))
            #Name1.append(line[3])
            #Name2.append(line[4])
            X[2].append(line[5])
            if line[6] == '':
                X[3].append(float('nan'))
            else:
                X[3].append(float(line[6]))
            X[4].append(int(line[7]))
            X[5].append(int(line[8]))
            #Ticket.append(int(line[9]))
            X[6].append(float(line[10]))
            #Cabin.append(int(line[11]))
            if line[12] == '':
                X[7].append(float('nan'))
            else:
                X[7].append(str(line[12]))      
           
        #female - 0
        #male - 1
        
        j = 0
        for i in X[2]:
            if i == 'male':
                X[2][j] = 1
            else:
                X[2][j] = 0
            j = j+1
        
        #C - 0
        #Q - 1
        #S - 2
        
        j = 0
        for i in X[7]:
            if i == 'C':
                X[7][j] = 0
            elif i == 'Q':
                X[7][j] = 1
            else:
                X[7][j] = 2
            j = j+1
            
        return X, y

print(import_data2('train.csv'))

([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 

# 5

In [10]:
#5a

def train_test_split(X, y, t_f):
    
    X_test, X_train = np.split(shuffle_data(X,y)[0],[int(t_f * len(X))]) 
    y_test, y_train = np.split(shuffle_data(X,y)[1],[int(t_f * len(y))]) 
    
    return X_train, y_train, X_test, y_test

print(train_test_split(X1, y1, 0.4)[0])
print('\n')
print(train_test_split(X1, y1, 0.4)[1])
print('\n')
print(train_test_split(X1, y1, 0.4)[2])
print('\n')
print(train_test_split(X1, y1, 0.4)[3])

[[ 40.    0.  178.  ...   2.4  24.7  49.1]
 [ 32.    1.  155.  ...   2.4  25.   46.6]
 [ 57.    0.  172.  ...   0.3  19.9  22.4]
 ...
 [ 39.    1.  164.  ...   1.3  24.1  33.7]
 [ 43.    0.  165.  ...  -0.8  -8.8 -13.2]
 [ 58.    1.  148.  ...   0.4   7.7  11.2]]


[ 1  1  1  9  1  6  1  1  1  1  1 10  3  2  6  1  4  1  1 10  4  2 10  3
  2  5  1  1 16 10  1 10  1 16 16  1 10  2  1  1  2  2  2  2  1  1  4  1
  3  9  7  2  1  1  6  1  1  6  1  1  1  1  1  5  1  1  2  1  1 10  1  1
  1  5 14  1  1  1  1  6  1  1  1  3  3  1 10  2 10  1  1  1 16  4  1  1
  1  2  1  1  1  9  1  2  2  1 16  3  5  1  4  6 16  6 10  1  1  2 10  1
  3  1  2  5  1 10  1  1 10  1  1 16  9  1  1  2  1 10  1  1  6  1  1  1
  1  2  2  2  6  3  1  1  1  1  1  1  6  2  1  4  2 10  7  1 16  2  1 16
  1  1  6  1  1  2 14 15 10  1  1  1  1  1  1  6  1  1  2  1  4 10  1  1
  1  1  5  1  1  1  4  1 10  1  1  1  1 10  1  1  1  1  1  1  1  4  1  3
  1  1  1  1 16  1 10  1  1 14  1  1  1  1  1  1  1 10  6  1  2  5  7  1
  1 

In [11]:
#5b

def train_test_CV_split(X, y, t_f, cv_f):
    
    X_test, X_train = np.split(shuffle_data(X,y)[0],[int(t_f*len(X))]) 
    y_test, y_train = np.split(shuffle_data(X,y)[1],[int(t_f*len(y))]) 
    
    X_train, X_cv = np.split(X_train,[int(cv_f*len(X_train))])
    y_train, y_cv = np.split(y_train,[int(cv_f*len(y_train))])
    
    return X_train, y_train, X_test, y_test, X_cv, y_cv

print(train_test_CV_split(X1, y1, 0.4, 0.3)[0])
print('\n')
print(train_test_CV_split(X1, y1, 0.4, 0.3)[1])
print('\n')
print(train_test_CV_split(X1, y1, 0.4, 0.3)[2])
print('\n')
print(train_test_CV_split(X1, y1, 0.4, 0.3)[3])
print('\n')
print(train_test_CV_split(X1, y1, 0.4, 0.3)[4])
print('\n')
print(train_test_CV_split(X1, y1, 0.4, 0.3)[5])

[[ 33.    1.  160.  ...   1.1  34.4  41.2]
 [ 54.    1.  160.  ...   1.    8.7  14.5]
 [ 48.    0.  157.  ...   0.8  41.6  52.8]
 ...
 [ 39.    1.  160.  ...   2.6  17.6  44.1]
 [ 47.    1.  163.  ...   0.7  17.9  22.3]
 [ 51.    0.  156.  ...   0.6   9.8  14.6]]


[ 6  1 10  1 10  1  6  1  1  1  1  1  1 10  1  1  1  5  1  1  1  2  2 16
  1 10  1  1  1  1 16  1 16  1  1  1 10  1  6  1  1 14  1 16  1 10  2 10
  1  5  2  1  1  3  3  1  1 10  6  2 10  1  1  1  2 16  5  1 10  2  1  6
  1  1 10  1 10  1  1  2  1]


[[ 57.    0.  175.  ...   1.5  12.7  26.2]
 [ 48.    1.  160.  ...  -1.2  24.4  12.9]
 [ 65.    0.  175.  ...  -0.5  16.6  12.7]
 ...
 [ 75.    1.  159.  ...  -3.7  88.8  43.7]
 [ 27.    1.  155.  ...   1.9  14.3  27.2]
 [ 36.    0.  185.  ...   0.9  39.6  45.7]]


[ 1  2  7  6  1  1  1  5  1  1  1  1  1  1  1 10  1  1  1 16  1  2  1  7
  6  9  1  4  2  8  1  2  1 14  1  2  1  2  1  6  1  1  3  6 16  1  2 14
  1  3  2  5  1  9  5  1 16  4  1 10  6  3  1  1  1  1  1  1  4  6  1  3